acl/urls.py
from django.conf.urls import url
from acl import views


urlpatterns = [
    url(r'^define_group/$', views.define_group, name='define_group'),
    url(r'^group_list/$', views.group_list, name='group_list'),
    url(r'^edit_group/(?P<_id>[\w\d]+)/$', views.edit_group, name='edit_group'),
    url(r'^delete_group/(?P<user_id>[\w\d]+)/$', views.delete_group, name='delete_group'),

    url(r'^add_user/$', views.add_user, name='add_user'),
    url(r'^user_list/$', views.user_list, name='user_list'),
    url(r'^user_shop_list/$', views.user_shop_list, name='user_shop_list'),
    url(r'^edit_username/(?P<user_id>[\w\d]+)/$', views.edit_username, name='edit_username'),
    url(r'^delete_user/(?P<user_id>[\w\d]+)/$', views.delete_user, name='delete_user'),
]

shop_dashboard/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.urlpatterns import format_suffix_patterns


urlpatterns = [
    url(r'^category/', include('category.urls')),
    url(r'^products/', include('product.urls')),
    url(r'^brand/', include('brand.urls')),
    url(r'^factor/', include('factor.urls')),
    url(r'^form/', include('sample_form.urls')),
    url(r'^users/', include('users.urls')),
    url(r'^acl/', include('acl.urls')),
    url(r'^amazing_offer/', include('amazing_offer.urls')),
    url(r'^banner/', include('banner.urls')),
    url(r'^color/', include('color.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

api_pattern = format_suffix_patterns([
    url(r'^rest-api/v1/', include('rest_api.urls')),
])

urlpatterns = urlpatterns + api_pattern + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

acl/models.py
from django.db import models
from django.contrib.auth.models import User as DjangoUser


class UserBox(models.Model):
    user = models.OneToOneField(DjangoUser)
    mongo_id = models.CharField(max_length=24)
    image_flag = models.BooleanField(default=False)
    group_name = models.CharField(max_length=50)

    def __unicode__(self):
        return self.user.username

acl/forms.py
# coding: utf-8

from django import forms
from utils import acl_visible_segment, acl_view_segment
from acl.func_tools import get_groups


class GroupForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(GroupForm, self).__init__(*args, **kwargs)

    group_name = forms.CharField(
        max_length=100,
        error_messages={'required': 'نام گروه را وارد کنید.'},
        label="نام گروه",
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'نام انگلیسی'})
    )
    visible_templatetags = forms.MultipleChoiceField(
        choices=acl_visible_segment.items(),
        required=False,
        label="دسترسی ها",
        widget=forms.CheckboxSelectMultiple(attrs={"class": "uk-grid"})
    )

    def clean(self, *args, **kwargs):
        form_data = super(GroupForm, self).clean()
        visible_templatetags = form_data.get('visible_templatetags')
        form_data_clean = {
            'visible_templatetags': visible_templatetags,
            'group_name': form_data.get('group_name'),
            'views': []
        }
        for template in visible_templatetags:
            form_data_clean['views'].extend(acl_view_segment.get(template, []))

        self.cleaned_data = form_data_clean


class UserForm(forms.Form):
    gender_option = (
        (1, 'آقا'),
        (2, 'خانم')
    )

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)

    username = forms.CharField(label='نام کاربری', max_length=15, required=True)
    password1 = forms.CharField(label='رمز عبور', widget=forms.PasswordInput, required=False)
    password2 = forms.CharField(label='تکرار و تایید رمز عبور', widget=forms.PasswordInput, required=False)
    group_name = forms.ChoiceField(
        label='گروه خود را انتخاب کنید',
        widget=forms.Select(attrs={'class': 'combo-large dash-groupname-combo'}),
        choices=get_groups().items(),
        required=True
    )
    first_name = forms.CharField(label='نام', required=True)
    last_name = forms.CharField(label='نام خانوادگی', required=True)
    email = forms.EmailField(label='آدرس صندوق الکترونیکی', required=True)
    gender = forms.ChoiceField(
        label='جنسیت:',
        choices=gender_option,
        widget=forms.RadioSelect(attrs={'tabindex': '3'})
    )

    def clean(self):
        cleaned_data = super(UserForm, self).clean()
        password1 = cleaned_data.get('password1', '')
        password2 = cleaned_data.get('password2', '')

        if password1 != password2:
            self.add_error('password1', 'رمز عبورهای وارد شده، یکسان نمی باشد.')

        if not (password1 and password2):
            cleaned_data.pop('password1', '')
            cleaned_data.pop('password2', '')

acl/views.py
from bson import ObjectId
from django.http import HttpResponseRedirect
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.views.decorators.http import require_POST
from acl.func_tools import group_query, insert_acl_group
from core.jalali import Jalali
from forms import GroupForm, UserForm
from core.db_mongo import cursor

import bcrypt
import datetime


def define_group(request):
    args = {}
    if request.method == 'POST':
        args['form'] = GroupForm(request.POST)
        if args['form'].is_valid():
            data = args['form'].cleaned_data
            insert = insert_acl_group(data)
            if insert:
                return HttpResponseRedirect('/acl/group_list')
            else:
                args['error'] = {'errors': {'insert error': 'insert was not successful'}}
        else:
            args['error'] = {'errors': args['form'].errors}

    args['form'] = GroupForm()
    return render(request, 'acl/define_group.html', args)


def group_list(request):
    args = {'data': list(cursor.acl_group.find())}
    for row in args['data']:
        row['id'] = row.pop('_id')

    return render(request, 'acl/group_list.html', args)


def edit_group(request, _id):
    args = {}
    initial = cursor.acl_group.find_one({'_id': ObjectId(_id)}, {'_id': 0})

    if request.POST:
        args['form'] = GroupForm(request.POST)
        if args['form'].is_valid():
            data = args['form'].cleaned_data
            update = group_query(data, _id)
            if update:
                return HttpResponseRedirect('/acl/group_list')
        else:
            args['error'] = {'errors': args['form'].errors}

    args['form'] = GroupForm(initial)

    return render(request, 'acl/edit_group.html', args)


@require_POST
def delete_group(request, _id):
    remove = cursor.acl_group.delete_one({'_id': ObjectId({'_id': _id})})
    return JsonResponse(remove, safe=False)


def delete_user(request, user_id):
    cursor.users.delete_one({'_id': ObjectId(user_id)})
    return redirect(user_list)


def add_user(request):
    context = {}

    if request.method != 'POST':
        form = UserForm()
    else:
        form = UserForm(request.POST)

        if not form.is_valid():
            context['errors'] = form.errors
        else:
            data = form.cleaned_data

            processed_data = {
                'personal': {
                    'first_name': data['first_name'],
                    'last_name': data['last_name'],
                },
                'group_name': data['group_name'],
                'username': data['username'].lower(),
                'gender': int(data['gender']),
                'password': data['password1'],
                'user_type': 'OPERATOR',
                'email': data['email'].lower(),
            }

            try:
                user_id = str(register_dashboard(processed_data))
            except Exception:
                context['errors'] = {'message': 'DuplicateKeyError'}
            else:
                return HttpResponseRedirect('/acl/user_list')

    context['form'] = form

    return render(request, 'acl/add_user.html', context)


def register_dashboard(data):
    password = data['password'].encode('utf-8')
    hashed = bcrypt.hashpw(password, bcrypt.gensalt(10))
    data['password'] = bcrypt.hashpw(password, hashed)
    data['created_date'] = datetime.datetime.now()
    return cursor.users.insert(data)


def user_list(request):
    args = {}
    new_data = []
    users = cursor.users.find({"user_type": "OPERATOR"})
    for user in users:
        doc = {
            'id': str(user['_id']),
            'username': user['username'],
            'group_name': user['group_name'],
            'full_name': user['personal']['first_name'] + " " + user['personal']['last_name'],
            'email': user['email']
        }

        new_data.append(doc)

    args['users'] = new_data
    return render(request, 'acl/user_list.html', args)


def edit_username(request, user_id):
    context = {}
    user = cursor.users.find_one({"_id": ObjectId(user_id), "user_type": "OPERATOR"})

    form = UserForm(request.POST or None, initial={
        'username': user['username'],
        'group_name': user['group_name'],
        'first_name': user['personal']['first_name'],
        'last_name': user['personal']['last_name'],
        'email': user['email'],
        'gender': user['gender'],
    })

    if request.method == 'POST':
        if form.is_valid():
            form_data = form.cleaned_data

            form_data['personal'] = {}
            if 'last_name' in form_data:
                form_data['personal']['last_name'] = form_data.pop('last_name')
            if 'first_name' in form_data:
                form_data['personal']['first_name'] = form_data.pop('first_name')

            if 'password' in form_data:
                password = form_data['password'].encode('utf-8')
                hashed = bcrypt.hashpw(password, bcrypt.gensalt(10))
                form_data['password'] = bcrypt.hashpw(password, hashed)

            cursor.users.update_one({'_id': ObjectId(user_id)}, {'$set': form_data})
            return HttpResponseRedirect('/acl/user_list')
        else:
            context['errors'] = form.errors

    context['form'] = form
    return render(request, 'acl/edit_username.html', context)


def user_shop_list(request):
    args = {}
    new_data = []
    users = cursor.users.find({"user_type": "USER"})
    for user in users:
        jalali_invoice_date = Jalali(user['created_date'])
        doc = {
            'id': str(user['_id']),
            'full_name': user.get('first_name', "") + " " + user.get('last_name', ""),
            'phone_number': user.get('phone_number'),
            'created_date': jalali_invoice_date.date_with_space,
            'code': user.get('code'),
        }

        new_data.append(doc)

    args['users'] = new_data
    return render(request, 'acl/user_shop_list.html', args)

templates/acl/add_user.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <h2>داشبورد</h2>
    <ul class="tm-breadcrumb uk-breadcrumb">
        <li><a href=""><i class="panda panda-home"></i></a></li>
        <li><span>پنل مدیریت</span></li>
        <li><span>کاربر ها</span></li>
        <li><span>کاربران</span></li>
        <li class="uk-active"><span>افزودن کاربر</span></li>
        <li class="uk-float-left"><span id="tm-date-and-time"></span></li>
    </ul>
    <div class="uk-panel uk-panel-box uk-panel-box-primary uk-form sh-newpro-first">
        <div class="sh-product-head">
            <h3 class="uk-panel-title"><i class="panda panda-user-plus"></i>افزودن کاربر</h3>
        </div>
        <form class="uk-form" method="POST">
            {% csrf_token %}
            <div class="sh-adduser-users">
                <p>افزودن کاربر :</p>
                {% for item in form %}
                    <div class="uk-form-row">
                        <label class="uk-form-label uk-text-left">{{ item.label }}</label>
                        <div class="uk-form-controls">{{ item }}</div>
                    </div>
                {% endfor %}
            </div>
            <div class="tm-panel-footer">
                <div class="uk-form-row uk-float-right">
                    <button class="sh-btn-4 uk-button" type="submit"><i class="panda panda-floppy-disk"></i>ذخیره</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}
{% block js_code %}
    {% if errors %}
        {% for field, error in errors.items %}
            uikitNotify('{{ error.0 }}', 'panda\&#32panda-cross', 'danger');
        {% endfor %}
    {% endif %}
{% endblock %}
{% block js_plugin %}
    <script>
        aside_dynamic('manage_users', 'manage_users-users');
        comboBox('#id_group_name');
        comboBox('.combo-large', 'combo-large');
    </script>
{% endblock %}

templates/acl/define_group.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <h2>داشبورد</h2>
    <ul class="tm-breadcrumb uk-breadcrumb">
        <li><a href=""><i class="panda panda-home"></i></a></li>
        <li><span>پنل مدیریت</span></li>
        <li><span>کاربر ها</span></li>
        <li><span>گروه ها</span></li>
        <li class="uk-active"><span>افزودن گروه</span></li>
        <li class="uk-float-left"><span id="tm-date-and-time"></span></li>
    </ul>
    <div class="uk-panel uk-panel-box uk-panel-box-primary uk-form sh-newpro-first">
        <div class="sh-product-head">
            <h3 class="uk-panel-title"><i class="panda panda-user-plus"></i>افزودن گروه</h3>
        </div>
        <form class="uk-form" method="POST">
            {% csrf_token %}
            <div class="sh-addgroup-users">
                <p class="uk-margin-large-bottom">گروه مورد نظر خود را تعریف نمایید :</p>
                {% for item in form %}
                    <div class="uk-form-row">
                        <label class="uk-form-label">{{ item.label }}</label>
                        <div class="uk-form-controls">{{ item }}</div>
                    </div>
                {% endfor %}
            </div>
            <div class="tm-panel-footer">
                <div class="uk-form-row uk-float-right">
                    <button class="sh-btn-4 uk-button" type="submit"><i class="panda panda-floppy-disk"></i>ذخیره</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}
{% block js_plugin %}
    <script>
        {% if errors %}
            {% for field, error in errors.items %}
                uikitNotify('{{ error.0 }}', 'panda\&#32panda-cross', 'danger');
            {% endfor %}
        {% endif %}
        aside_dynamic('manage_users', 'manage_users_group');
    </script>
{% endblock %}

templates/acl/edit_group.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <h2>داشبورد</h2>
    <ul class="tm-breadcrumb uk-breadcrumb">
        <li><a href=""><i class="panda panda-home"></i></a></li>
        <li><span>پنل مدیریت</span></li>
        <li><span>کاربر ها</span></li>
        <li><span>گروه ها</span></li>
        <li class="uk-active"><span>ویرایش گروه</span></li>
        <li class="uk-float-left"><span id="tm-date-and-time"></span></li>
    </ul>
    <div class="uk-panel uk-panel-box uk-panel-box-primary uk-form sh-newpro-first">
        <div class="sh-product-head">
            <h3 class="uk-panel-title"><i class="panda panda-user-plus"></i>افزودن گروه</h3>
        </div>
        <form class="uk-form" method="POST">
            {% csrf_token %}
            <div class="sh-addgroup-users">
                <p class="uk-margin-large-bottom">گروه مورد نظر خود را تعریف نمایید :</p>
                {% for item in form %}
                    <div class="uk-form-row">
                        <label class="uk-form-label">{{ item.label }}</label>
                        <div class="uk-form-controls">{{ item }}</div>
                    </div>
                {% endfor %}
            </div>
            <div class="tm-panel-footer">
                <div class="uk-form-row uk-float-right">
                    <button class="sh-btn-4 uk-button" type="submit"><i class="panda panda-floppy-disk"></i>ذخیره</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}
{% block js_plugin %}
    <script>
        {% if errors %}
            {% for field, error in errors.items %}
                uikitNotify('{{ error.0 }}', 'panda\&#32panda-cross', 'danger');
            {% endfor %}
        {% endif %}
        aside_dynamic('manage_users', 'manage_users_group');
    </script>
{% endblock %}

templates/acl/edit_username.html
{% extends "base.html" %}
{% load static %}
{% block meta_head %}
    <link rel="stylesheet" href="{% static "css/jalalidate.css" %}">
    <link href="{% static 'css/selectbox/jquery.selectBox.css' %}" rel="stylesheet">
{% endblock %}
{% block content %}
    <h2>داشبورد</h2>
    <ul class="tm-breadcrumb uk-breadcrumb">
        <li><a href=""><i class="panda panda-home"></i></a></li>
        <li><span>پنل مدیریت</span></li>
        <li><span>کاربر ها</span></li>
        <li><span>کاربران</span></li>
        <li class="uk-active"><span>ویرایش کاربران</span></li>
        <li class="uk-float-left"><span id="tm-date-and-time"></span></li>
    </ul>
    <div class="uk-panel uk-panel-box uk-panel-box-primary uk-form sh-newpro-first">
        <div class="sh-product-head">
            <h3 class="uk-panel-title"><i class="panda panda-pencil"></i>ویرایش کاربران</h3>
        </div>
        <form class="uk-form" method="POST">
            {% csrf_token %}
            <div class="sh-adduser-users">
                <p>ویرایش کاربران</p>
                {% for item in form %}
                    <div class="uk-form-row">
                        <label class="uk-form-label uk-text-left">{{ item.label }}</label>
                        <div class="uk-form-controls">{{ item }}</div>
                    </div>
                {% endfor %}
                <div class="tm-panel-footer">
                    <button class="sh-btn-4 uk-button" type="submit"><i class="panda panda-floppy-disk"></i>ذخیره</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}
{% block uikit_js %}
    <script src="{% static "js/components/form-select.min.js" %}"></script>
    <script src="{% static 'js/jquery.selectBox.js' %}"></script>
{% endblock %}
{% block js_plugin%}
    <script>
        $('#id_group_name').selectBox({
            menuTransition: 'fade',
            menuSpeed:'fast',
        });
        $(".selectBox-dropdown-menu").mCustomScrollbar({theme:"dark-thin"});
        aside_dynamic ('manage_users','manage_users-users');
    </script>
{% endblock %}
{% block js_code %}
    {% if errors %}
        {% for field, error in errors.items %}
            uikitNotify('{{ error.0 }}', 'panda\&#32panda-cross', 'danger');
        {% endfor %}
    {% endif %}
{% endblock %}

templates/acl/group_list.html
{% extends "base.html" %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static "css/calendar-blue.css" %}">
{% endblock %}
{% block content %}
    <h2>داشبورد</h2>
    <ul class="tm-breadcrumb uk-breadcrumb">
        <li><a href=""><i class="panda panda-home"></i></a></li>
        <li><span>پنل مدیریت</span></li>
        <li><span>کاربرها</span></li>
        <li class="uk-active"><span>گروه ها</span></li>
        <li class="uk-float-left"><span id="tm-date-and-time"></span></li>
    </ul>
    <div class="uk-panel uk-panel-box uk-form">
        <h3 class="uk-panel-title">
            <i class="panda panda-menu"></i>لیست گروه ها
        </h3>
        <div class="tm-panel-header">
            <a class="uk-button sh-btn-2" href="{% url 'define_group' %}"><i class="panda panda-plus"></i>افزودن گروه
            </a>
        </div>
        <table class="uk-table sh-groups-tables">
            <thead>
            <tr>
                <th>ردیف</th>
                <th>نام گروه</th>
                <th>موارد قابل مشاهده</th>
                <th>آخرین ویرایش</th>
                <th>عملیات</th>
            </tr>
            </thead>
            <tbody>
            {% for item in data %}
                <tr data-id="{{ item.id }}" data-group-name="{{ item.group_name }}">
                    <td>{{ forloop.counter }}</td>
                    {% for key, value in item.items %}
                        {% if key != 'id' %}
                            {% if key == 'visible_templatetags' or key == 'views' %}
                                <td><strong title="{% for i in value %} {{ i }} <br> {% endfor %}">{{ value|length }} items</strong></td>
                            {% else %}
                                <td>{{ value|truncatewords:8 }}</td>
                            {% endif %}
                        {% endif %}
                    {% endfor %}
                    <td>
                        <a class="uk-button sh-btn-7" href="{% url 'edit_group' item.id %}"><i class="panda panda-pencil"></i>ویرایش</a>
                        <a class="uk-button sh-btn-6" id="table-remove-button" data-value="{% url 'delete_group' item.id %}"><i class="panda panda-cross"></i>پاک کردن</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <div class="tm-panel-footer">
            <a class="uk-button sh-btn-2" href="{% url 'define_group' %}"><i class="panda panda-plus"></i>افزودن گروه</a>
        </div>
    </div>
{% endblock %}
{% block uikit_js %}
    <script src="{% static "js/components/form-select.min.js" %}"></script>
{% endblock %}
{% block js_plugin %}
    <script>
        aside_dynamic('manage_users', 'manage_users_group');
    </script>
{% endblock %}
{% block js_code %}
    {% if errors %}
        {% for field, error in errors.items %}
            uikitNotify('{{ error.0 }}', 'panda\&#32panda-cross', 'danger');
        {% endfor %}
    {% endif %}
    <script>
        $('a#table-remove-button').on('click', function (e) {
            e.preventDefault();

            var dataID = this.dataset.value;
            var dataTr = $(this).parents('tr');

            UIkit.modal.confirm('آیا مطمين هستید ؟', function () {
                $.ajax({
                    url: dataID,
                    type: 'POST',
                    dataType: 'json',
                    success: function (data, textStatus, xhr) {
                        $(dataTr).remove();
                    },
                    error: function (e) {
                        notify_error(e, true)
                    }
                });
            });
        });
    </script>
{% endblock %}

templates/acl/user_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <h2>داشبورد</h2>
    <ul class="tm-breadcrumb uk-breadcrumb">
        <li><a href=""><i class="panda panda-home"></i></a></li>
        <li><span>پنل مدیریت</span></li>
        <li><span>کاربرها</span></li>
        <li class="uk-active"><span>کاربران</span></li>
        <li class="uk-float-left"><span id="tm-date-and-time"></span></li>
    </ul>
    <div class="uk-panel uk-panel-box uk-form">
        <h3 class="uk-panel-title">
            <i class="panda panda-menu"></i>لیست کاربران
        </h3>
        <div class="tm-panel-header">
            <a class="uk-button sh-btn-2" href="{% url 'add_user' %}"><i class="panda panda-plus"></i>افزودن کاربر
            </a>
        </div>
        <table class="uk-table sh-users-tables">
            <thead>
            <tr>
                <th>ردیف</th>
                <th>نام و نام خانوادگی</th>
                <th>نام کاربری</th>
                <th>پست الکترونیک</th>
                <th>نام گروه</th>
                <th>عملیات</th>
            </tr>
            </thead>
            <tbody>
            {% for item in users %}
                <tr data-id="{{ item.id }}">
                    <td>{{ forloop.counter }}</td>
                    <td>{{ item.full_name }}</td>
                    <td>{{ item.username }}</td>
                    <td>{{ item.email }}</td>
                    <td>{{ item.group_name }}</td>
                    <td>
                        <a class="uk-button sh-btn-7" href="{% url 'edit_username' item.id %}"><i class="panda panda-pencil"></i>ویرایش کردن</a>
                        <a class="uk-button sh-btn-6" href="{% url 'delete_user' item.id %}"><i class="panda panda-cross"></i>پاک کردن</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <div class="tm-panel-footer">
            <a class="uk-button sh-btn-2" href="{% url 'add_user' %}"><i class="panda panda-plus"></i>افزودن کاربر
            </a>
        </div>
    </div>
{% endblock %}
{% block uikit_js %}
    <script src="{% static "js/components/form-select.min.js" %}"></script>
{% endblock %}
{% block js_code %}
    {% if error %}
        {% for field, error in errors.items %}
            uikitNotify('{{ error.0 }}', 'panda\&#32panda-cross', 'danger');
        {% endfor %}
    {% endif %}
    <script>
        aside_dynamic('manage_users', 'manage_user_list');
        e.preventDefault();
    </script>
{% endblock %}

templates/acl/user_shop_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <h2>داشبورد</h2>
    <ul class="tm-breadcrumb uk-breadcrumb">
        <li><a href=""><i class="panda panda-home"></i></a></li>
        <li><span>پنل مدیریت</span></li>
        <li><span>کاربرها</span></li>
        <li class="uk-active"><span>کاربران</span></li>
        <li class="uk-float-left"><span id="tm-date-and-time"></span></li>
    </ul>
    <div class="uk-panel uk-panel-box uk-form">
        <h3 class="uk-panel-title">
            <i class="panda panda-menu"></i>لیست کاربران
        </h3>
        <div class="tm-panel-header">
            <a class="uk-button sh-btn-2" href="{% url 'add_user' %}"><i class="panda panda-plus"></i>افزودن کاربر
            </a>
        </div>
        <table class="uk-table sh-users-tables">
            <thead>
            <tr>
                <th>ردیف</th>
                <th>نام و نام خانوادگی</th>
                <th>شماره تلفن</th>
                <th>تاریخ ایجاد</th>
                <th>اخرین کد</th>
            </tr>
            </thead>
            <tbody>
            {% for item in users %}
                <tr data-id="{{ item.id }}">
                    <td>{{ forloop.counter }}</td>
                    <td>{{ item.full_name }}</td>
                    <td>{{ item.phone_number }}</td>
                    <td>{{ item.created_date }}</td>
                    <td>{{ item.code }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <div class="tm-panel-footer">
            <a class="uk-button sh-btn-2" href="{% url 'add_user' %}"><i class="panda panda-plus"></i>افزودن کاربر
            </a>
        </div>
    </div>
{% endblock %}
{% block uikit_js %}
    <script src="{% static "js/components/form-select.min.js" %}"></script>
{% endblock %}
{% block js_code %}
    {% if error %}
        {% for field, error in errors.items %}
            uikitNotify('{{ error.0 }}', 'panda\&#32panda-cross', 'danger');
        {% endfor %}
    {% endif %}
    <script>
        aside_dynamic('manage_users', 'manage_user_list');
        e.preventDefault();
    </script>
{% endblock %}