acl/urls.py
from django.conf.urls import url
from acl import views


urlpatterns = [
    url(r'^define_group/$', views.define_group, name='define_group'),
    url(r'^group_list/$', views.group_list, name='group_list'),
    url(r'^edit_group/(?P<_id>[\w\d]+)/$', views.edit_group, name='edit_group'),
    url(r'^delete_group/(?P<user_id>[\w\d]+)/$', views.delete_group, name='delete_group'),

    url(r'^add_user/$', views.add_user, name='add_user'),
    url(r'^user_list/$', views.user_list, name='user_list'),
    url(r'^user_shop_list/$', views.user_shop_list, name='user_shop_list'),
    url(r'^edit_username/(?P<user_id>[\w\d]+)/$', views.edit_username, name='edit_username'),
    url(r'^delete_user/(?P<user_id>[\w\d]+)/$', views.delete_user, name='delete_user'),
]

brand/urls.py
from django.conf.urls import url
from brand.views import brands, add_or_edit_brand, delete_brand, find_brand_by_id

urlpatterns = [
    url(r'^$', brands, name='brands'),
    url(r'^add_brand/$', add_or_edit_brand, name='add_or_edit_brand'),
    url(r'^delete_brand/$', delete_brand, name='delete_brand'),
    url(r'^find_brand_by_id/$', find_brand_by_id, name='find_brand_by_id'),
]

shop_dashboard/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.urlpatterns import format_suffix_patterns


urlpatterns = [
    url(r'^category/', include('category.urls')),
    url(r'^products/', include('product.urls')),
    url(r'^brand/', include('brand.urls')),
    url(r'^factor/', include('factor.urls')),
    url(r'^form/', include('sample_form.urls')),
    url(r'^users/', include('users.urls')),
    url(r'^acl/', include('acl.urls')),
    url(r'^amazing_offer/', include('amazing_offer.urls')),
    url(r'^banner/', include('banner.urls')),
    url(r'^color/', include('color.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

api_pattern = format_suffix_patterns([
    url(r'^rest-api/v1/', include('rest_api.urls')),
])

urlpatterns = urlpatterns + api_pattern + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

brand/forms.py
# coding: utf-8
from django import forms
from product.controller import CategoryController


class AddBrandForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(AddBrandForm, self).__init__(*args, **kwargs)

    fa_name = forms.CharField(
        label='نام فارسی',
        error_messages={'required': 'فیلد نام فارسی خالی می باشد.'},
        required=True,
        widget=forms.TextInput(attrs={'class': 'form_brand_data'})
    )
    en_name = forms.CharField(
        label='نام انگلیسی',
        error_messages={'required': 'فیلد نام انگلیسی خالی می باشد.'},
        required=True,
        widget=forms.TextInput(attrs={'class': 'form_brand_data'})
    )
    image = forms.FileField(
        label='لوگو',
        required=False,
        widget=forms.FileInput(attrs={
            'class': 'form_brand_data',
            'dispaly': 'none'
        })
    )
    brand_id = forms.CharField(
        widget=forms.HiddenInput(),
        required=False
    )
    page_name = forms.CharField(
        widget=forms.HiddenInput(),
        required=False
    )


class CategoryGroupForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(CategoryGroupForm, self).__init__(*args, **kwargs)
        self.fields['category'].choices = CategoryController().get_all_category_tuple()
        first_category_id = int(self.fields['category'].choices[0][0])
        self.fields['group'].choices = CategoryController().get_group_from_category_list(first_category_id)

    category = forms.ChoiceField(
        label='رسته',
        widget=forms.Select(attrs={'onchange': 'load_group()'}),
        error_messages={'required': 'رسته انتخاب نشده است.'},
        required=False
    )
    group = forms.ChoiceField(
        label='گروه',
        widget=forms.Select(attrs={}),
        error_messages={'required': 'گروه انتخاب نشده است.'},
        required=False
    )

brand/controller.py
from django.conf import settings
from core.db_mongo import cursor


def get_all_brand_by_category_group(category_group):
    criteria = {
        'status': True,
        'category_group': {'$elemMatch': {"id": category_group}},
    }
    return cursor.brand.find(criteria, settings.BRAND_GENERAL_PROJECTION)

brand/views.py
# coding: utf-8

import os
import logging
import shutil

import datetime
from PIL import Image
from pymongo import ReturnDocument

from forms import AddBrandForm
from bson.json_util import loads
from django.conf import settings
from django.shortcuts import render
from brand.forms import CategoryGroupForm
from core.db_mongo import get_next_sequence
from django.http import HttpResponse, JsonResponse
from django.views.decorators.http import require_POST
from core.db_mongo import cursor

logger = logging.getLogger(__name__)


def brands(request):
    criteria = {
        'status': True
    }
    args = {
        'all_brand': cursor.brand.find(criteria, {'_id': 0}).sort([("created_date", -1)]),
        'brand_form': AddBrandForm(initial={'page_name': 'brands'}),
        'category_form': CategoryGroupForm()
    }
    return render(request, 'brand/brands.html', args)


def add_or_edit_brand(request):
    response = {}
    brand_form = AddBrandForm(request.POST)
    if brand_form.is_valid():
        response = get_some_data_from_brand(request)
        criteria = {'$or': [{'fa_name': response['fa_name']}, {'en_name': response['en_name']}]}
        find_brand = cursor.brand.find_one(criteria)
        if request.POST['brand_id']:
            response['brand_id'] = int(request.POST['brand_id'])
            response['image'] = "/media/brand/" + str(response['brand_id']) + '.jpg'
            edit_brand(request, response, find_brand)
        else:
            add_brand(request, response, find_brand)

    else:
        response['message'] = 'form_error'
        response['error'] = brand_form.errors

    if "_id" in response:
        del response["_id"]
    return HttpResponse(
        JsonResponse(response),
        content_type='application/json')


def add_brand(request, response, find_brand):
    if not find_brand:
        response['brand_id'] = get_next_sequence('brand_id')
        response['image'] = "/media/brand/" + str(response['brand_id']) + '.jpg'
        response['created_date'] = datetime.datetime.now()
        query_send = cursor.brand.insert_one(response)
        if not query_send:
            response['message'] = 'query_error'
        else:
            if 'image' in request.FILES:
                save_image_brand(request.FILES['image'], response['brand_id'])
            else:
                shutil.copyfile(
                    settings.BASE_DIR + settings.DEFAULT_IMAGE_BRAND,
                    settings.BASE_DIR + "/media/brand/" + str(response['brand_id']) + '.jpg'
                )

            response['message'] = 'insert'
    else:
        response['message'] = 'repeat_error'


def edit_brand(request, response, find_brand):
    brand_id = response['brand_id']
    if find_brand:
        if find_brand['brand_id'] == brand_id:
            response['image'] = find_brand['image']
            if 'image' in request.FILES:
                save_image_brand(request.FILES['image'], brand_id)

            update_query = cursor.brand.update_one(
                {"brand_id": brand_id},
                {
                    '$set': response,
                    '$unset': {'reason_report': 1, 'user_id': 1}
                }).raw_result
            if not update_query:
                response['message'] = 'query_error'
            else:
                response['message'] = 'update'

        else:
            response['message'] = 'repeat_error'
    else:
        if 'image' in request.FILES:
            save_image_brand(request.FILES['image'], brand_id)

        update_query = cursor.brand.update_one(
            {"brand_id": brand_id},
            {
                '$set': response,
                '$unset': {'reason_report': 1, 'user_id': 1}
            }).raw_result
        if not update_query:
            response['message'] = 'query_error'


def get_some_data_from_brand(request):
    response = {
        'fa_name': request.POST['fa_name'].strip(),
        'en_name': request.POST['en_name'].strip(),
        'category_group': loads(request.POST['category_group']),
        'status': True
    }
    return response


def remove_image_brand(address_image):
    image = settings.BASE_DIR + address_image
    os.remove(image)


def save_image_brand(image_file, image_name):
    image_address_django = '/media' + settings.BRAND_IMAGE + str(image_name) + ".jpg"
    image = settings.MEDIA_ROOT + settings.BRAND_IMAGE + str(image_name) + ".jpg"
    img = Image.open(image_file)
    img = img.resize((38, 30), Image.ANTIALIAS)
    img.save(image, quality=100)
    return image_address_django


@require_POST
def delete_brand(request):
    response = {}
    data = request.POST
    brand_id = int(data['brand_id'])

    query_delete = cursor.brand.find_one_and_delete(
        {"brand_id": brand_id},
        return_document=ReturnDocument.BEFORE
    )
    if not query_delete:
        response['message'] = 'query_error'
    else:
        response['message'] = "delete"
        remove_image_brand(query_delete['image'])

    return HttpResponse(
        JsonResponse(response),
        content_type='application/json')


@require_POST
def find_brand_by_id(request):
    data = request.POST
    projection = {'user_id': 0}
    find_brand = cursor.brand.find_one({"brand_id": int(data['brand_id'])}, projection)
    if not find_brand:
        find_brand['message'] = 'query_error'
    else:
        find_brand['id'] = str(find_brand.pop('_id'))

    return HttpResponse(
        JsonResponse(find_brand),
        content_type='application/json')

templates/brand/blockbrands.html
{% extends "brand/brand_base.html" %}
{% load static %}
{% block content %}
    <h2>داشبورد</h2>
    <ul class="tm-breadcrumb uk-breadcrumb">
        <li><a href=""><i class="panda panda-home"></i></a></li>
        <li><span>پنل مدیریت</span></li>
        <li><span>مدیریت برند ها</span></li>
        <li class="uk-active"><span>رد شده ها</span></li>
        <li class="uk-float-left"><span id="tm-date-and-time"></span></li>
    </ul>
    <div class="uk-panel uk-panel-box uk-panel-box-primary">
        <div class="sh-product-head">
            <h3 class="uk-panel-title">
                <i class="panda panda-profile"></i>رد شده ها
            </h3>
        </div>
        {% if all_block_brand %}
            <ul class="uk-grid uk-grid-width-1-6">
                {% for word in all_block_brand %}
                    <li class="sh-filter-worlds" id="{{ word|mongo_id }}">
                        <a onclick="delete_brand_word('{{ word|mongo_id }}')"><i class="panda panda-cross"></i></a>
                        <span>{{ word.word }}</span>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <div class="uk-text-center"><p class="sh-comment-none-exist">در حال حاضر هیچ برندی رد نشده است.</p></div>
        {% endif %}
    </div>
{% endblock content %}
{% block js_brand %}
    <script>
        csrf_token = '{{ csrf_token }}';
        aside_dynamic ('manage_brands','manage_brands_block');
    </script>
{% endblock %}

templates/brand/brand_base.html
{% extends "base.html" %}
{% load static %}
{% block meta_head %}
{% endblock %}
{% block content %}
{% endblock content %}
{% block modal %}
    <div id="form_brand_modal" class="uk-modal">
        <div class="sh-edit-brand uk-modal-dialog" style="background: #FFFFFF">
            <a class="uk-modal-close uk-close"></a>
            <div class="uk-modal-header">افزودن برند</div>
            <div class="uk-grid uk-grid-medium">
                <form class="uk-form" id="form_add_brand" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ brand_form.page_name }}
                    {{ brand_form.brand_id }}
                    <p>{{ brand_form.fa_name.label }} :</p> {{ brand_form.fa_name }}
                    <p>{{ brand_form.en_name.label }} :</p> {{ brand_form.en_name }}
                    <div class="sh-select-picbrand">
                        <p>{{ brand_form.image.label }} :</p>
                        <div class="uk-form-file">
                            <button class="uk-button sh-btn-9">Choose File</button>
                            {{ brand_form.image }}
                        </div>
                        <img src="" id="image">
                    </div>
                    <div class="sh-catgrp">
                        <p>{{ category_form.category.label }} و {{ category_form.group.label }} را انتخاب نمایید:</p> {{ category_form.category }} {{ category_form.group }}
                        <a class="sh-btn-2 uk-button" onclick="add_category_group_to_brand()"><i class="panda panda-plus"></i>افزودن</a>
                    </div>
                    <div>
                        <table class="uk-table sh-allbrands-table">
                            <thead>
                                <tr>
                                    <th>رسته</th>
                                    <th>گروه</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody id="all_category_group"></tbody>
                        </table>
                    </div>
                </form>
            </div>
            <div class="uk-modal-footer">
                <div class="sh-btm-btn">
                    <a class="sh-btn-4 uk-button uk-float-left" onclick="add_or_edit_brand()"><i class="panda panda-floppy-disk"></i>ذخیره</a>
                    <a class="sh-btn-3 uk-button uk-modal-close"><i class="panda panda-cross"></i>انصراف</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block uikit_js %}
{% endblock %}
{% block js_plugin %}
    <script src="{% static "js/brand.js" %}"></script>
    <script src="{% static 'js/jquery.selectBox.js' %}"></script>
    <script>
        $('#id_category').selectBox({
            menuTransition: 'fade',
            menuSpeed:'fast'
        });
        $('#id_group').selectBox({
            menuTransition: 'fade',
            menuSpeed:'fast'
        });
        $(".selectBox-dropdown-menu").mCustomScrollbar({theme:"dark-thin"});

        csrf_token = '{{ csrf_token }}';
        function load_group() {
            $.ajax({
                url: '{% url "load_group" %}',
                type: 'POST',
                async: false,
                data: {
                    'category': $("#id_category").val(),
                    'csrfmiddlewaretoken': csrf_token
                },
                success: function (result) {
                    $("#id_group").html('');

                    for (var i = 0; i < result['result'].length; i++) {
                        $("#id_group").append('<option value="' + result['result'][i][0] + '">' + result['result'][i][1] + '</option>');
                    }
                    $('#id_group').selectBox('refresh');
                    $(".selectBox-dropdown-menu").mCustomScrollbar({theme:"dark-thin"});
                }
            })
        }

        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $('#image').removeClass('uk-hidden');
                    $('#image').attr('src', e.target.result);
                };
                reader.readAsDataURL(input.files[0]);
            }
        }
        $("#id_image").change(function(){
            readURL(this);
        });

    </script>
    {% block js_brand %}
    {% endblock %}
{% endblock %}
{% block js_code %}
{% endblock %}

templates/brand/brands.html
{% extends "brand/brand_base.html" %}
{% load static %}
{% block content %}
    <h2>داشبورد</h2>
    <ul class="tm-breadcrumb uk-breadcrumb">
        <li><a href=""><i class="panda panda-home"></i></a></li>
        <li><span>پنل مدیریت</span></li>
        <li><span>مدیریت برند ها</span></li>
        <li class="uk-active"><span>برند ها</span></li>
        <li class="uk-float-left"><span id="tm-date-and-time"></span></li>
    </ul>
    <div class="uk-panel uk-panel-box uk-panel-box-primary sh-brands-details">
        <div class="sh-product-head">
            <h3 class="uk-panel-title">
                <i class="panda panda-profile"></i>برند ها
            </h3>
        </div>
        <div class="tm-panel-header">
            <a class="sh-btn-2 uk-button" href="#form_brand_modal" data-uk-modal="{center:true, bgclose:false}"><i class="panda panda-plus"></i>افزودن برند</a>
        </div>
        <table class="uk-table sh-brands-table">
            <thead>
            <tr>
                <th>ردیف</th>
                <th>نام فارسی</th>
                <th>نام انگلیسی</th>
                <th>لوگو</th>
                <th>عملیات</th>
            </tr>
            </thead>
            <tbody id="brand">
            {% for brand in all_brand %}
                <tr id="brand_{{ brand.brand_id }}">
                    <td class="count_brand">{{ forloop.counter }}</td>
                    <td>{{ brand.fa_name|truncatechars:10 }}</td>
                    <td>{{ brand.en_name|truncatechars:10 }}</td>
                    <td><img style="height: 24px" src="{{ brand.image }}"></td>
                    <td class="uk-float-left">
                        <button class="sh-btn-7 uk-button" onclick="set_data_to_modal_for_edit('{{ brand.brand_id }}', 'brands')"><i class="panda panda-pencil"></i>ویرایش</button>
                        <button class="sh-btn-6 uk-button" onclick="delete_brand('{{ brand.brand_id }}', 'delete_brand', 'None')"><i class="panda panda-bin"></i>پاک کردن</button>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <div class="tm-panel-footer">
            <a class="sh-btn-2 uk-button" href="#form_brand_modal" data-uk-modal="{center:true, bgclose:false}"><i class="panda panda-plus"></i>افزودن برند</a>
        </div>
    </div>
{% endblock content %}
{% block js_brand %}
    <script>
        csrf_token = '{{ csrf_token }}';
        aside_dynamic ('manage_brands','manage_brands_all');
    </script>
{% endblock %}

templates/brand/pendingbrands.html
{% extends "brand/brand_base.html" %}
{% block content %}
    <h2>داشبورد</h2>
    <ul class="tm-breadcrumb uk-breadcrumb">
        <li><a href=""><i class="panda panda-home"></i></a></li>
        <li><span>پنل مدیریت</span></li>
        <li><span>مدیریت برند ها</span></li>
        <li class="uk-active"><span>در انتظار تایید</span></li>
        <li class="uk-float-left"><span id="tm-date-and-time"></span></li>
    </ul>
    <div class="uk-panel uk-panel-box uk-panel-box-primary">
        <div class="sh-product-head">
            <h3 class="uk-panel-title">
                <i class="panda panda-clipboard"></i>در انتظار تایید
            </h3>
        </div>
        {% if all_brand %}
            <table class="uk-table sh-brands-pending">
                <thead>
                <tr>
                    <th>ردیف</th>
                    <th>نام فارسی</th>
                    <th>نام انگلیسی</th>
                    <th>لوگو</th>
                    <th>توضیحات</th>
                    <th>عملیات</th>
                    </tr>
                </thead>
            <tbody id="brand">
                {% for brand in all_brand %}
                    <tr id="brand_{{ brand.brand_id }}">
                        <td class="count_brand">{{ forloop.counter0 }}</td>
                        <td>{{ brand.fa_name|truncatechars:10}}</td>
                        <td>{{ brand.en_name|truncatechars:10}}</td>
                        <td><img style="height: 24px" src="{{ brand.image }}"></td>
                        {% if brand.reason_report == 'category_group' and brand.status %}
                            <td style="color: #e28327">اضافه شدن دسته و گروه جدید به برند</td>
                            <td class="uk-float-left">
                                <button class="sh-btn-7 uk-button" onclick="set_data_to_modal_for_edit('{{ brand.brand_id }}', 'pending')"><i class="panda panda-pencil"></i>ویرایش و تایید کردن</button>
                                <button class="sh-btn-6 uk-button" onclick="delete_brand('{{ brand.brand_id }}', 'category_group', '{{ brand.user_id }}')"><i class="panda panda-cross"></i>رد کردن</button>
                            </td>
                        {% else %}
                            <td style="color: #35ADE4">برند جدید</td>
                            <td class="uk-float-left">
                                <button class="sh-btn-7 uk-button" onclick="set_data_to_modal_for_edit('{{ brand.brand_id }}', 'pending')"><i class="panda panda-pencil"></i>ویرایش و تایید کردن</button>
                                <button class="sh-btn-6 uk-button" onclick="delete_brand('{{ brand.brand_id }}', 'word_filtering', '{{ brand.user_id }}')">فیلترینگ واژه نامناسب</button>
                                <button class="sh-btn-6 uk-button" onclick="delete_brand('{{ brand.brand_id }}', 'brand_filtering', '{{ brand.user_id }}')">برند نامعتبر</button>
                                <button class="sh-btn-6 uk-button" onclick="delete_brand('{{ brand.brand_id }}', 'delete_brand', '{{ brand.user_id }}')"><i class="panda panda-cross"></i>پاک کردن</button>
                            </td>
                        {% endif %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
            <div class="uk-text-center"><p>در حال حاضر هیچ برندی در انتظار تایید نیست.</p></div>
        {% endif %}
    </div>
{% endblock content %}
{% block js_brand %}
    <script>
        csrf_token = '{{ csrf_token }}';
        aside_dynamic ('manage_brands', 'manage_brands_pend');
    </script>
{% endblock %}