acl/urls.py
from django.conf.urls import url
from acl import views


urlpatterns = [
    url(r'^define_group/$', views.define_group, name='define_group'),
    url(r'^group_list/$', views.group_list, name='group_list'),
    url(r'^edit_group/(?P<_id>[\w\d]+)/$', views.edit_group, name='edit_group'),
    url(r'^delete_group/(?P<user_id>[\w\d]+)/$', views.delete_group, name='delete_group'),

    url(r'^add_user/$', views.add_user, name='add_user'),
    url(r'^user_list/$', views.user_list, name='user_list'),
    url(r'^user_shop_list/$', views.user_shop_list, name='user_shop_list'),
    url(r'^edit_username/(?P<user_id>[\w\d]+)/$', views.edit_username, name='edit_username'),
    url(r'^delete_user/(?P<user_id>[\w\d]+)/$', views.delete_user, name='delete_user'),
]

banner/urls.py
from django.conf.urls import url

from banner import views

urlpatterns = [
    url(r'^$', views.banner_list, name='banner_list'),
    url(r'^add/$', views.banner_add, name='banner_add'),
    url(r'^edit/(?P<banner_id>.+)$', views.banner_edit, name='banner_edit'),
    url(r'^delete$', views.banner_delete, name='banner_delete'),
]

shop_dashboard/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.urlpatterns import format_suffix_patterns


urlpatterns = [
    url(r'^category/', include('category.urls')),
    url(r'^products/', include('product.urls')),
    url(r'^brand/', include('brand.urls')),
    url(r'^factor/', include('factor.urls')),
    url(r'^form/', include('sample_form.urls')),
    url(r'^users/', include('users.urls')),
    url(r'^acl/', include('acl.urls')),
    url(r'^amazing_offer/', include('amazing_offer.urls')),
    url(r'^banner/', include('banner.urls')),
    url(r'^color/', include('color.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

api_pattern = format_suffix_patterns([
    url(r'^rest-api/v1/', include('rest_api.urls')),
])

urlpatterns = urlpatterns + api_pattern + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

banner/forms.py
# coding: utf-8
from django import forms


class BannerForm(forms.Form):
    name = forms.CharField(
        label='نام',
        error_messages={'required': 'فیلد نام خالی می باشد.'},
    )
    link = forms.CharField(
        label='لینک',
        error_messages={'required': 'فیلد لینک خالی می باشد.'},
    )
    color = forms.CharField(
        label='رنگ',
        error_messages={'required': 'فیلد رنگ خالی می باشد.'},
    )
    image = forms.ImageField(
        label='انتخاب عکس',
        required=False,
    )

    def __init__(self, *args, **kwargs):
        self.image_optional = kwargs.pop('image_optional', True)

        super(BannerForm, self).__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = super(BannerForm, self).clean()
        if self.image_optional is False and not cleaned_data.get('image', None):
            self.add_error('image', 'فیلد عکس خالی می باشد.')

banner/controller.py
from PIL import Image
from django.conf import settings


def save_image(image_file, image_name):
    image_address_django = '/media' + settings.BANNER_IMAGE + str(image_name) + ".jpg"
    image = settings.MEDIA_ROOT + settings.BANNER_IMAGE + str(image_name) + ".jpg"
    img = Image.open(image_file)
    # img = img.resize((img.size[0], 24), Image.ANTIALIAS)
    img.save(image, quality=100)

    return image_address_django

banner/views.py
import datetime

from django.shortcuts import render
from django.views.decorators.http import require_POST
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, JsonResponse

from banner.forms import BannerForm
from banner.controller import save_image
from core.db_mongo import cursor
from bson.json_util import ObjectId


def banner_list(request):
    banners = list(cursor.banner.find())
    for banner in banners:
        banner['id'] = str(banner.pop('_id'))
    return render(request, 'banner/list.html', {'banners': banners})


def banner_add(request):
    if request.method != "POST":
        form = BannerForm()
    else:
        form = BannerForm(request.POST)
        if form.is_valid():
            form_data = form.cleaned_data

            form_data['image'] = save_image(
                request.FILES['image'],
                datetime.datetime.now().strftime('%Y%M%d%H%M%S')
            )
            form_data['created_date'] = datetime.datetime.now()
            cursor.banner.insert_one(form_data)

            return HttpResponseRedirect(reverse(banner_list))

    return render(request, 'banner/add.html', {'form': form})


def banner_edit(request, banner_id):
    if request.method != "POST":
        banner = cursor.banner.find_one({'_id': ObjectId(banner_id)})
        banner['id'] = str(banner.pop('_id'))

        form = BannerForm(banner)
    else:
        form = BannerForm(request.POST)
        if form.is_valid():
            form_data = form.cleaned_data

            if 'image' in request.FILES:
                form_data['image'] = save_image(
                    request.FILES['image'],
                    datetime.datetime.now().strftime('%Y%M%d%H%M%S')
                )
            else:
                form_data.pop('image', None)

            cursor.banner.update_one(
                {'_id': ObjectId(banner_id)},
                {'$set': form_data}
            )
            return HttpResponseRedirect(reverse(banner_list))

    return render(request, 'banner/edit.html', {'form': form, 'image': banner['image']})


@require_POST
def banner_delete(request):
    result = cursor.banner.delete_one(
        {'_id': ObjectId(request.POST['banner_id'])}
    ).deleted_count

    return JsonResponse({'result': result})

templates/banner/add.html
{% extends "base.html" %}
{% load static %}
{% block meta_head %}
     <link rel="stylesheet" type="text/css" href="{% static "css/colorpicker.css" %}" />
{% endblock %}
{% block content %}
    <h2>داشبورد</h2>
    <ul class="tm-breadcrumb uk-breadcrumb">
        <li><a href="#"><i class="panda panda-home"></i></a></li>
        <li><span>پنل مدیریت</span></li>
        <li><span>مدیریت سایت</span></li>
        <li><span>بنر</span></li>
        <li class="uk-active"><span>افزودن بنر</span></li>
        <li class="uk-float-left"><span id="tm-date-and-time"></span></li>
    </ul>
    <form enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        <div class="uk-panel uk-panel-box uk-panel-box-primary uk-form dash-addsticker uk-form-row">
            <div class="sh-product-head">
                <h3 class="uk-panel-title">
                    <i class="panda panda-profile"></i>افزودن بنر
                </h3>
            </div>
            <label class="uk-margin-small-left">{{ form.name.label }} :</label>{{ form.name }}
            <label class="uk-margin-small-left uk-margin-large-right">{{ form.link.label }} :</label>{{ form.link }}
            <label class="uk-margin-small-left uk-margin-large-right">{{ form.color.label }} :</label>{{ form.color }}
            <div class="uk-form-row">
                <div class="dash-addsticker-details">
                    <div class="uk-form-file">
                        <label style="vertical-align:baseline;">{{ form.image.label }}:</label>{{ form.image }}
                        <button class="sh-btn-9">Choose File</button>
                    </div>
                    <img class="uk-margin-large-right uk-hidden" src="{{ image }}" id="image">
                </div>
            </div>
            <div class="tm-panel-footer">
                <a class="sh-btn-3 uk-button" href="{% url 'banner_list' %}"><i class="panda panda-cross"></i>انصراف</a>
                <button class="sh-btn-4 uk-button" type="submit"><i class="panda panda-floppy-disk"></i>ذخیره</button>
            </div>
        </div>
    </form>

{% endblock content %}
{% block js_code %}
    <script src="{% static "js/colorpicker.js" %}"></script>

    <script>
        aside_dynamic('site_management', 'banner_management');

        {% if form.errors %}
            {% for field in form %}
                {% for error in field.errors %}
                 uikitNotify('{{ error }}', 'panda\&#32panda-warning', 'warning');
                {% endfor %}
            {% endfor %}
        {% endif %}

        function delete_banner(banner_id){
            UIkit.modal.confirm('آیا مطمین هستید ؟', function () {
                var data = {
                    'banner_id': banner_id,
                    'csrfmiddlewaretoken': '{{ csrf_token }}'
                };
                $.ajax({
                    url: '{% url "banner_delete" %}',
                    type: 'POST',
                    data: data,
                    success: function (result) {
                        if(result['message'] == 'success'){
                            $('#'+banner_id).remove();
                            uikitNotify('محصول از پیشنهاد ویژه پاک شد.', 'panda\&#32panda-cross', 'success');
                        }else{
                            notify_error(500, false)
                        }
                    },
                    error: function (e) {
                        notify_error(e, true)
                    }
                })
            }, {labels: {'Ok': 'بلی', 'Cancel': 'خیر'}});
        }

        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $('#image').removeClass('uk-hidden');
                    $('#image').attr('src', e.target.result);
                };
                reader.readAsDataURL(input.files[0]);
            }
        }
        $("#id_image").change(function(){
            readURL(this);
        });

        $('input#id_color').ColorPicker({
            color: '#EFEFEF',
            onShow: function (colpkr) {
                $(colpkr).fadeIn(500);
                return false;
            },
            onHide: function (colpkr) {
                $(colpkr).fadeOut(500);
                return false;
            },
            onChange: function (hsb, hex, rgb) {
                $('input#id_color').css('backgroundColor', '#' + hex);
                $('input#id_color').val("#" + hex);
            }
        });
    </script>
{% endblock %}
{% block js_plugin %}
{% endblock %}

templates/banner/edit.html
{% extends "base.html" %}
{% load static %}
{% block meta_head %}
     <link rel="stylesheet" type="text/css" href="{% static "css/colorpicker.css" %}" />
{% endblock %}
{% block content %}
    <h2>داشبورد</h2>
    <ul class="tm-breadcrumb uk-breadcrumb">
        <li><a href="#"><i class="panda panda-home"></i></a></li>
        <li><span>پنل مدیریت</span></li>
        <li><span>مدیریت سایت</span></li>
        <li><span>بنر</span></li>
        <li class="uk-active"><span>ویرایش بنر</span></li>
        <li class="uk-float-left"><span id="tm-date-and-time"></span></li>
    </ul>
    <form enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        <div class="uk-panel uk-panel-box uk-panel-box-primary uk-form dash-addsticker uk-form-row">
            <div class="sh-product-head">
                <h3 class="uk-panel-title">
                    <i class="panda panda-profile"></i>ویرایش بنر
                </h3>
            </div>
            <label class="uk-margin-small-left">{{ form.name.label }} :</label>{{ form.name }}
            <label class="uk-margin-small-left uk-margin-large-right">{{ form.link.label }} :</label>{{ form.link }}
            <label class="uk-margin-small-left uk-margin-large-right">{{ form.color.label }} :</label>{{ form.color }}
            <div class="uk-form-row">
                <div class="dash-addsticker-details">
                    <div class="uk-form-file">
                        <label style="vertical-align:baseline;">{{ form.image.label }}:</label>{{ form.image }}
                        <button class="sh-btn-9">Choose File</button>
                    </div>
                    <img class="uk-margin-large-right" src="{{ image }}" id="image">
                </div>
            </div>
            <div class="tm-panel-footer">
                <a class="sh-btn-3 uk-button" href="{% url 'banner_list' %}"><i class="panda panda-cross"></i>انصراف</a>
                <button class="sh-btn-4 uk-button" type="submit"><i class="panda panda-floppy-disk"></i>ذخیره</button>
            </div>
        </div>
    </form>

{% endblock content %}
{% block js_code %}
    <script src="{% static "js/colorpicker.js" %}"></script>

    <script>
        aside_dynamic('site_management', 'banner_management');

        {% if form.errors %}
            {% for field in form %}
                {% for error in field.errors %}
                 uikitNotify('{{ error }}', 'panda\&#32panda-warning', 'warning');
                {% endfor %}
            {% endfor %}
        {% endif %}

        function delete_banner(banner_id){
            UIkit.modal.confirm('آیا مطمین هستید ؟', function () {
                var data = {
                    'banner_id': banner_id,
                    'csrfmiddlewaretoken': '{{ csrf_token }}'
                };
                $.ajax({
                    url: '{% url "banner_delete" %}',
                    type: 'POST',
                    data: data,
                    success: function (result) {
                        if(result['message'] == 'success'){
                            $('#'+banner_id).remove();
                            uikitNotify('محصول از پیشنهاد ویژه پاک شد.', 'panda\&#32panda-cross', 'success');
                        }else{
                            notify_error(500, false)
                        }
                    },
                    error: function (e) {
                        notify_error(e, true)
                    }
                })
            }, {labels: {'Ok': 'بلی', 'Cancel': 'خیر'}});
        }

        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $('#image').removeClass('uk-hidden');
                    $('#image').attr('src', e.target.result);
                };
                reader.readAsDataURL(input.files[0]);
            }
        }
        $("#id_image").change(function(){
            readURL(this);
        });

        $('input#id_color').ColorPicker({
            color: '#EFEFEF',
            onShow: function (colpkr) {
                $(colpkr).fadeIn(500);
                return false;
            },
            onHide: function (colpkr) {
                $(colpkr).fadeOut(500);
                return false;
            },
            onChange: function (hsb, hex, rgb) {
                $('input#id_color').css('backgroundColor', '#' + hex);
                $('input#id_color').val("#" + hex);
            }
        });
    </script>
{% endblock %}
{% block js_plugin %}
{% endblock %}

templates/banner/list.html
{% extends "base.html" %}
{% load static %}
{% block meta_head %}
{% endblock %}
{% block content %}
    <h2>داشبورد</h2>
    <ul class="tm-breadcrumb uk-breadcrumb">
        <li><a href=""><i class="panda panda-home"></i></a></li>
        <li><span>پنل مدیریت</span></li>
        <li><span>مدیریت سایت</span></li>
        <li class="uk-active"><span>بنر</span></li>
        <li class="uk-float-left"><span id="tm-date-and-time"></span></li>
    </ul>
    <div class="uk-panel uk-panel-box uk-panel-box-primary sh-brands-details">
        <div class="sh-product-head">
            <h3 class="uk-panel-title">
                <i class="panda panda-profile"></i>بنر
            </h3>
        </div>
        <div class="tm-panel-header">
            <a id="add-form" class="sh-btn-2 uk-button" href="{% url 'banner_add' %}"><i class="panda panda-plus"></i>افزودن بنر</a>
        </div>
        <table class="uk-table sh-brands-allbrands">
            <thead>
            <tr>
                <th>ردیف</th>
                <th>نام</th>
                <th>لینک</th>
                <th>رنگ</th>
                <th>عکس</th>
                <th>عملیات</th>
            </tr>
            </thead>
            <tbody id="sample_form">
            {% for banner in banners %}
                <tr id="{{ banner.id }}">
                    <td>{{ forloop.counter0 }}</td>
                    <td>{{ banner.name|truncatechars:20 }}</td>
                    <td>{{ banner.link }}</td>
                    <td>{{ banner.color }}</td>
                    <td><img src="{{ banner.image }}" style="height: 20px;width: 40px"></td>
                    <td class="uk-float-left">
                        <a href="{% url 'banner_edit' banner.id %}" class="sh-btn-7 uk-button"><i class="panda panda-pencil"></i>ویرایش</a>
                        <a onclick="delete_banner('{{ banner.id }}')" class="sh-btn-6 uk-button"><i class="panda panda-bin"></i>پاک کردن</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <div class="tm-panel-footer">
            <a id="add-form" class="sh-btn-2 uk-button" href="{% url 'banner_add' %}"><i class="panda panda-plus"></i>افزودن بنر</a>
        </div>
    </div>

{% endblock content %}
{% block js_code %}
    <script>
        aside_dynamic('site_management', 'banner_management');

        function delete_banner(banner_id){
            UIkit.modal.confirm('آیا مطمین هستید ؟', function () {
                var data = {
                    'banner_id': banner_id,
                    'csrfmiddlewaretoken': '{{ csrf_token }}'
                };
                $.ajax({
                    url: '{% url "banner_delete" %}',
                    type: 'POST',
                    data: data,
                    success: function (result) {
                        $('#'+banner_id).remove();
                        uikitNotify('بنر مورد نظر از لیست بنرها حذف شد.', 'panda\&#32panda-cross', 'success');
                    },
                    // error: function (e) {
                    //     notify_error(e, true)
                    // }
                })
            }, {labels: {'Ok': 'بلی', 'Cancel': 'خیر'}});

        }
    </script>
{% endblock %}
{% block js_plugin %}
{% endblock %}