acl/urls.py
from django.conf.urls import url
from acl import views


urlpatterns = [
    url(r'^define_group/$', views.define_group, name='define_group'),
    url(r'^group_list/$', views.group_list, name='group_list'),
    url(r'^edit_group/(?P<_id>[\w\d]+)/$', views.edit_group, name='edit_group'),
    url(r'^delete_group/(?P<user_id>[\w\d]+)/$', views.delete_group, name='delete_group'),

    url(r'^add_user/$', views.add_user, name='add_user'),
    url(r'^user_list/$', views.user_list, name='user_list'),
    url(r'^user_shop_list/$', views.user_shop_list, name='user_shop_list'),
    url(r'^edit_username/(?P<user_id>[\w\d]+)/$', views.edit_username, name='edit_username'),
    url(r'^delete_user/(?P<user_id>[\w\d]+)/$', views.delete_user, name='delete_user'),
]

product/urls.py
from django.conf.urls import url
from product.views import product_list, update_product,\
    update_json_product, create_product,\
    create_json_product, create_product_id, delete_product,\
    product_trashed, pagination_product, change_product_to_trash,\
    load_group, load_gallery_to_show, delete_gallery,\
    change_main_gallery, change_product_published, \
    find_one_product_by_id, edit_color_product

urlpatterns = [
    url(r'^$', product_list, name='productList'),
    url(r'^update/(?P<product_id>\d+)$', update_product, name='update_product'),
    url(r'^update_json_product/$', update_json_product, name='update_json_product'),

    url(r'^create/product_id$', create_product_id, name='create_product_id'),
    url(r'^create/(?P<product_id>\d+)$', create_product, name='create_product'),
    url(r'^create_json_product/$', create_json_product, name='create_json_product'),

    url(r'^delete/$', delete_product, name='delete_product'),

    url(r'^trash/$', product_trashed, name='product_trashed'),
    url(r'^pagination/$', pagination_product, name='paginationProduct'),
    url(r'^trash/pagination/$', pagination_product, name='paginationProduct'),
    url(r'^change_product_to_trash/$', change_product_to_trash, name='change_Product_To_Trash'),

    url(r'^loadGroup/$', load_group, name='load_group'),

    url(r'^load_gallery/$', load_gallery_to_show,  name='load_gallery_to_show'),
    url(r'^delete_gallery/$', delete_gallery, name='delete_gallery'),
    url(r'^change_main_gallery/$', change_main_gallery, name='change_main_gallery'),

    url(r'^change_product_published/$', change_product_published, name='change_product_published'),

    url(r'^find/one/', find_one_product_by_id, name='find_one_product_by_id'),

    url(r'^edit_color_product/', edit_color_product, name='edit_color_product'),
]

shop_dashboard/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.urlpatterns import format_suffix_patterns


urlpatterns = [
    url(r'^category/', include('category.urls')),
    url(r'^products/', include('product.urls')),
    url(r'^brand/', include('brand.urls')),
    url(r'^factor/', include('factor.urls')),
    url(r'^form/', include('sample_form.urls')),
    url(r'^users/', include('users.urls')),
    url(r'^acl/', include('acl.urls')),
    url(r'^amazing_offer/', include('amazing_offer.urls')),
    url(r'^banner/', include('banner.urls')),
    url(r'^color/', include('color.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

api_pattern = format_suffix_patterns([
    url(r'^rest-api/v1/', include('rest_api.urls')),
])

urlpatterns = urlpatterns + api_pattern + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/forms.py
# coding: utf-8

from django import forms
from product.statics import (
    YES_OR_NO,
    PUBLISHED,
    PRODUCT_PER_PAGE,
    EXIST_PRODUCT,
    EXIST_PRODUCT_FILTERS,
    GENDER,
    COUNTRY_CHOICE_DICT,
    COLOR_STATUS,
    UNIT_TYPE)


class ProductForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)

    product_id = forms.IntegerField(
        label='کد محصول',
        widget=forms.TextInput(attrs={'readonly': 'readonly'})
    )
    product_name_fa = forms.CharField(
        label='نام محصول به فارسی',
        error_messages={'required': 'فیلد نام نباید خالی باشد.'},
    )
    product_name_en = forms.CharField(
        label='نام محصول به انگلیسی',
        error_messages={'required': 'فیلد نام لاتین نباید خالی باشد.'},
    )
    national_code = forms.ChoiceField(
        label='کشور سازنده',
        choices=COUNTRY_CHOICE_DICT.items(),
        widget=forms.Select(attrs={'class': 'select_search'}),
        required=False
    )
    gender = forms.ChoiceField(
        label='جنسیت',
        choices=GENDER,
        widget=forms.Select(attrs={}),
        required=False
    )

    brand = forms.CharField(
        label='برند:',
        widget=forms.Select(attrs={'class': 'select_search'}),
        required=False
    )
    exist = forms.ChoiceField(
        label='وضعیت',
        choices=EXIST_PRODUCT,
        widget=forms.Select(attrs={}),
        required=False
    )

    general_specifications = forms.CharField(
        widget=forms.Textarea,
        required=False
    )
    gift = forms.CharField(
        label='کد محصول مورد نظر را وارد نمایید',
        widget=forms.TextInput(attrs={'type': "text"}),
        required=False
    )
    advantages = forms.CharField(
        label='نقاط قوت',
        widget=forms.TextInput(attrs={'class': "advantages"}),
        required=False
    )
    disadvantages = forms.CharField(
        label='نقاط ضعف',
        widget=forms.TextInput(attrs={'class': "disadvantages"}),
        required=False
    )
    color_status = forms.ChoiceField(
        label="نوع رنگ بندی خود را انتخاب نمایید:",
        choices=COLOR_STATUS,
        required=False,
        widget=forms.RadioSelect(attrs={'onclick': "changeColorStatus()"})
    )

    def clean(self, *args, **kwargs):
        form_data = super(ProductForm, self).clean()
        extra_field = (
            'csrfmiddlewaretoken',
            'gallery_image',
            'tags',
            'list_advantages',
            'list_disadvantages',
            'color',
            "product_id"
        )
        int_field = ('exist', 'brand', 'gender')

        form_data_clean = {}
        for field in form_data:
            if field in extra_field or form_data.get(field) == "" or form_data.get(field) is None:
                continue

            if field in int_field:
                form_data_clean[field] = int(form_data.get(field))
                continue
            form_data_clean[field] = form_data.get(field)

        if 'general_specifications' not in form_data_clean:
            form_data_clean['general_specifications'] = ""

        self.cleaned_data = form_data_clean


class GeneralProductForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(GeneralProductForm, self).__init__(*args, **kwargs)

    product_id = forms.IntegerField(
        label='کد محصول',
        widget=forms.TextInput(attrs={'readonly': 'readonly'})
    )
    product_name_fa = forms.CharField(
        label='نام محصول به فارسی',
        error_messages={'required': 'فیلد نام نباید خالی باشد.'},
    )
    product_name_en = forms.CharField(
        label='نام محصول به انگلیسی',
        error_messages={'required': 'فیلد نام لاتین نباید خالی باشد.'},
    )
    national_code = forms.ChoiceField(
        label='کشور سازنده',
        choices=COUNTRY_CHOICE_DICT.items(),
        widget=forms.Select(attrs={'class': 'select_search'}),
        required=False
    )
    gender = forms.ChoiceField(
        label='جنسیت',
        choices=GENDER,
        widget=forms.Select(attrs={}),
        required=False
    )

    brand = forms.CharField(
        label='برند:',
        widget=forms.Select(attrs={'class': 'select_search'}),
        required=False
    )
    exist = forms.ChoiceField(
        label='وضعیت',
        choices=EXIST_PRODUCT,
        widget=forms.Select(attrs={}),
        required=False
    )

    sell = forms.IntegerField(
        label='قیمت فروش',
        widget=forms.TextInput(attrs={'type': "text"}),
        error_messages={'required': 'قیمت فروش را وارد کنید.'},
        required=False
    )
    buy = forms.IntegerField(
        label='قیمت خرید',
        widget=forms.TextInput(),
        error_messages={'required': 'قیمت خرید را وارد کنید.'},
        required=False
    )
    unit = forms.FloatField(
        label='واحد',
        widget=forms.TextInput(),
        error_messages={'required': 'واحد را وارد کنید.'},
        required=True
    )
    unit_type = forms.ChoiceField(
        label='نوع',
        widget=forms.Select(attrs={}),
        choices=UNIT_TYPE,
        error_messages={'required': 'نوع واحد را وارد کنید.'},
        required=True
    )

    def clean(self, *args, **kwargs):
        form_data = super(GeneralProductForm, self).clean()
        if form_data.get('exist') == '1':
            if form_data.get('sell') and not isinstance(form_data.get('sell'), int):
                self.add_error("sell", "قیمت فروش درست وارد نشده است.")

            if form_data.get('buy') and not isinstance(form_data.get('buy'), int):
                self.add_error("buy", "قیمت خرید درست وارد نشده است.")

        extra_field = ('csrfmiddlewaretoken', "product_id")
        int_field = ('sell', 'buy', 'exist', 'brand', 'gender')
        float_field = ('unit',)

        form_data_clean = {}
        for field in form_data:
            if field in extra_field or form_data.get(field) == "" or form_data.get(field) is None:
                continue

            if field in int_field:
                form_data_clean[field] = int(form_data.get(field))
                continue

            if field in float_field:
                form_data_clean[field] = float(form_data.get(field))

            form_data_clean[field] = form_data.get(field)

        self.cleaned_data = form_data_clean


class FilterForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(FilterForm, self).__init__(*args, **kwargs)

    exist = forms.ChoiceField(
        choices=EXIST_PRODUCT_FILTERS,
        label="وضعیت محصول",
        widget=forms.Select(attrs={'onchange': 'paginator(1)'})
    )
    published = forms.ChoiceField(
        choices=PUBLISHED,
        label="وضعیت انتشار",
        widget=forms.Select(attrs={'onchange': 'paginator(1)'})
    )
    product_per_page = forms.ChoiceField(
        choices=PRODUCT_PER_PAGE,
        widget=forms.Select(attrs={'onchange': 'paginator(1)'})
    )
    min_price = forms.IntegerField(
        widget=forms.TextInput(attrs={'onchange': 'paginator(1)', 'placeholder': "کمترین قیمت"})
    )
    max_price = forms.IntegerField(
        widget=forms.TextInput(attrs={'onchange': 'paginator(1)', 'placeholder': "بیشترین قیمت"})
    )
    search = forms.CharField(
        widget=forms.TextInput(attrs={'onchange': 'paginator(1)', 'placeholder': 'جستجوی محصول ...'})
    )
    trash = forms.CharField(widget=forms.HiddenInput())


class PriceProductForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(PriceProductForm, self).__init__(*args, **kwargs)

    product_id = forms.CharField(
        widget=forms.HiddenInput(),
        error_messages={'required': 'مودال راببندید و دوباره باز کنید.'},
    )

    sell = forms.IntegerField(
        label='قیمت فروش',
        widget=forms.TextInput(attrs={'type': "text", 'class': 'uk-float-right'}),
        error_messages={'required': 'قیمت فروش را وارد کنید.'},
    )
    buy = forms.IntegerField(
        label='قیمت خرید',
        widget=forms.TextInput(attrs={'type': "text", 'class': 'uk-float-right'}),
        error_messages={'required': 'قیمت خرید را وارد کنید.'},
    )
    old_sell = forms.IntegerField(
        widget=forms.HiddenInput(),
        required=False
    )
    old_buy = forms.IntegerField(
        widget=forms.HiddenInput(),
        required=False
    )

templates/product/create_product.html
{% extends "base.html" %}
{% load static %}
{% block meta_head %}
    <link href="{% static 'css/cropper.css' %}" rel="stylesheet" xmlns="http://www.w3.org/1999/html">
    <link href="{% static 'css/trumbowyg.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/select2.css' %}" rel="stylesheet">
    <link href="{% static 'css/selectbox/jquery.selectBox.css' %}" rel="stylesheet">
{% endblock %}
{% block content %}
    <h2>داشبورد</h2>
    <ul class="tm-breadcrumb uk-breadcrumb">
        <li><a><i class="panda panda-home"></i></a></li>
        <li><span>پنل مدیریت</span></li>
        <li><span>محصولات</span></li>
        <li class="uk-active"><span>تکمیل محتوا</span></li>
        <li class="uk-float-left"><span id="tm-date-and-time"></span></li>
    </ul>
    <div class="uk-panel uk-panel-box uk-panel-box-primary">
        <h3 class="uk-panel-title"><i class="panda panda-qrcode"></i>تکمیل محتوا</h3>

        <div class="tm-panel-header uk-clearfix">
            <h2>Product ID: <span>PPID-{{ product_id }}</span></h2>
            <a class="sh-btn-3 uk-button" href="{% url 'productList' %}"><i class="panda panda-cross"></i>انصراف</a>
            <button class="add_product_submit sh-btn-4 uk-button" onclick="createProduct()"><i class="panda panda-floppy-disk"></i>ذخیره</button>
        </div>
        <ul class="tm-tab uk-tab" data-uk-switcher="{connect:'#sh-details-products', animation:'fade'}">
            <li class="uk-active"><a>اطلاعات کلی</a></li>
            <li><a>قیمت محصول</a></li>
            <li><a>رنگ بندی محصول</a></li>
        </ul>
        <input type="hidden" id="update_product" value="{{ update_product }}">
        <div class="uk-form uk-form-horizontal sh-create-newproduct-tab">
            <ul id="sh-details-products" class="tm-switcher-product uk-switcher">
                <li id="general-info">
                    <div class="uk-form-row">
                        {{ form.suggested_id }}
                        <label class="uk-form-label uk-text-left">{{ form.product_id.label }}:</label>

                        <div class="uk-form-controls">{{ form.product_id }}</div>
                    </div>

                    <div class="uk-form-row">
                        <label class="uk-form-label uk-text-left">{{ form.product_name_fa.label }}:</label>
                        <div class="uk-form-controls">{{ form.product_name_fa }}</div>
                    </div>

                    <div class="uk-form-row">
                        <label class="uk-form-label uk-text-left">{{ form.product_name_en.label }}:</label>
                        <div class="uk-form-controls">{{ form.product_name_en }}</div>
                    </div>
                    <div class="uk-form-row">
                        <label class="uk-form-label uk-text-left">{{ form.unit.label }}:</label>
                        <div class="uk-form-controls">{{ form.unit }}</div>
                    </div>
                    <div class="uk-form-row">
                        <label class="uk-form-label uk-text-left">{{ form.unit_type.label }}:</label>
                        <div class="uk-form-controls">{{ form.unit_type }}</div>
                    </div>
                    <div class="uk-form-row">
                        <label class="uk-form-label uk-text-left">{{ form.gender.label }}:</label>
                        <div class="uk-form-controls">{{ form.gender }}</div>
                    </div>

                    <div class="uk-form-row">
                        <label class="uk-form-label uk-text-left">{{ form.brand.label }}</label>
                        <div class="uk-form-controls">
                            <select id="id_brand" name="brand" class="select_search">
                                {% for brand in brands %}
                                    <option value="{{ brand.brand_id }}" {% if brand.brand_id == product_brand %}selected{% endif %}>{{ brand.en_name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>

                    <div class="uk-form-row">
                        <label class="uk-form-label uk-text-left">{{ form.national_code.label }}:</label>
                        <div class="uk-form-controls">{{ form.national_code }}</div>
                    </div>
                    <div class="uk-form-row">
                        <label class="uk-form-label uk-text-left">{{ form.exist.label }}:</label>
                        <div class="uk-form-controls">{{ form.exist }}</div>
                    </div>
                </li>
                <li>
                    <div class="uk-form-row">
                        <input id="old_sell" type="hidden" value="{{ form.sell.value }}">
                        <label class="uk-form-label uk-text-left sh-margin-medium-top">{{ form.buy.label }}:</label>
                        <div class="uk-form-controls">{{ form.buy }}</div>
                    </div>

                    <div class="uk-form-row">
                        <input id="old_buy" type="hidden" value="{{ form.buy.value }}">
                        <label class="uk-form-label uk-text-left sh-margin-medium-top">{{ form.sell.label }}:</label>
                        <div class="uk-form-controls">{{ form.sell }}</div>
                    </div>
                </li>
                <li>
                    <div id="Color">
                        <select name="color" class="select_color" id="selected_colors">
                            {% for color in all_color %}
                                <option value="{{ color.code }}" data-code="{{ color.code }}" data-presentation="{{ color.presentation }}">
                                    {{ color.presentation }}
                                </option>
                            {% endfor %}
                        </select>
                        <a class="sh-btn-2 uk-button uk-margin-small-right" onclick="addColor()"><i class="panda panda-plus"></i>افزودن</a>
                        <div id="colors" class="uk-margin-large-top uk-margin-large-right">
                            {% for item in product_colors %}
                                <a id="color_{{ item.code }}" class="sh-btn-10 uk-button"><i class="panda panda-cross" onclick="removeColor('{{ item.code }}')"></i>{{ item.presentation }}</a>
                            {% endfor %}
                        </div>
                    </div>
                </li>
            </ul>
        </div>

        <div class="tm-panel-footer">
            <a class="sh-btn-3 uk-button" href="{% url 'productList' %}"><i class="panda panda-cross"></i>انصراف</a>
            <button class="add_product_submit sh-btn-4 uk-button" onclick="createProduct()"><i class="panda panda-floppy-disk"></i>ذخیره</button>
        </div>
    </div>
{% endblock %}
{% block js_plugin %}
    <script src="{% static 'js/select2.full.min.js' %}"></script>
    <script src="{% static 'js/jquery.selectBox.js' %}"></script>
    <script src="{% static 'js/colors.js' %}"></script>
{% endblock %}
{% block js_code %}
    <script>
        aside_dynamic('manage_products', 'manage_products_all');

        csrf_token = '{{ csrf_token }}';

        $('#id_gender').selectBox({
            menuTransition: 'fade',
            menuSpeed: 'fast'
        });
        $('#id_exist').selectBox({
            menuTransition: 'fade',
            menuSpeed: 'fast'
        });
        $('#id_unit_type').selectBox({
            menuTransition: 'fade',
            menuSpeed: 'fast'
        });

        $('.select_color').select2({'width': '15%'});

        $(".selectBox-dropdown-menu").mCustomScrollbar({theme: "dark-thin"});
        $(".select2-results").mCustomScrollbar({theme: "dark-thin"});

        $('.select_search').select2();

        {% for item in product_colors %}
            colors.push({code: '{{ item.code }}', presentation: '{{ item.presentation }}'});
        {% endfor %}


        var product_data = {};
        function createProduct() {
            UIkit.modal.confirm("آیا می خواهید تغییرات ذخیره شود؟", function () {
                $('#general-info').find("input[name], select[name]").each(function (index, node) {
                    product_data[node.name] = node.value;
                });
                product_data['colors'] = JSON.stringify(colors);
                product_data['price_change'] = JSON.stringify(checkPriceIsChange());
                product_data['csrfmiddlewaretoken'] = csrf_token;
                $('.add_product_submit').attr('disabled', 'disabled');
                $.ajax({
                    url: '{% url 'create_json_product' %}',
                    type: 'POST',
                    data: product_data,
                    success: function (result) {
                        $('.add_product_submit').removeAttr('disabled');
                        if (result['message'] == 'insert') {
                            uikitNotify('محصول با موفقیت اضافه شد.', 'panda\&#32panda-checkmark2', 'success');

                        } else if (result['message'] == 'update') {
                            uikitNotify('محصول به روز رسانی شد.', 'panda\&#32panda-checkmark2', 'success');

                        } else if (result['message'] == 'color_error') {
                            uikitNotify('محصول با رنگی که پاک شده در انبار وجود دارد', 'panda\&#32panda-warning', 'warning');
                            for (var color in remove_colors) {
                                colors.push(remove_colors[color]);
                                var html = '<a id="color_' + remove_colors[color].code + '" class="sh-btn-10 uk-button" style="margin-left:5px;"><i class="panda panda-cross" onclick="removeColor(\'' + remove_colors[color].code + '\')"></i>' + remove_colors[color].presentation + '</a>';
                                $("#colors").append(html)
                            }
                            remove_colors = []

                        } else if (result['message'] == 'session_error') {
                            uikitNotify('دوباره امتحان کنید.', 'panda\&#32panda-warning', 'warning');
                            setTimeout(function () {
                                window.location.href = "{% url 'productList'%}";
                            }, 1000);

                        } else if (result['message'] == 'form_error') {
                            for (var value in result['result']) {
                                uikitNotify(result['result'][value], 'panda\&#32panda-cross', 'danger');
                            }

                        } else if (result['message'] == 'error') {
                            notify_error(500, false)
                        }
                    },
                    error: function (e) {
                        notify_error(e, true)
                    }
                });
            });
        }

        function checkPriceIsChange() {
            var price_change = false,
                old_buy = $("#old_buy").val(),
                old_sell = $("#old_sell").val(),
                new_buy = $('#id_buy').val(),
                new_sell = $('#id_sell').val();
            if (old_buy != new_buy || old_sell != new_sell) {
                product_data['sell'] = $('#id_sell').val();
                product_data['buy'] = $('#id_buy').val();
                price_change = true
            }
            return price_change
        }

    </script>
{% endblock %}

templates/product/products.html
{% extends "base.html" %}
{% load static %}
{% block meta_head %}
    <link href="{% static 'css/selectbox/jquery.selectBox.css' %}" rel="stylesheet">
{% endblock %}
{% block content %}
    <h2>داشبورد</h2>
    <ul class="tm-breadcrumb uk-breadcrumb">
        <li><a href=""><i class="panda panda-home"></i></a></li>
        <li><span>پنل مدیریت</span></li>
        <li><span>محصولات</span></li>
        <li class="uk-active"><span>همه محصولات</span></li>
        <li class="uk-float-left"><span id="tm-date-and-time"></span></li>
    </ul>
    <div class="uk-panel uk-panel-box uk-panel-box-primary">
        <div class="sh-product-head">
            <h3 class="uk-panel-title">
                <i class="panda panda-folder-open"></i>لیست محصولات
            </h3>
            <div class="sh-title-menu">
                <a href="{% url 'create_product_id' %}">
                    <i class="panda panda-clipboard"></i>
                    ایجاد محصول جدید
                </a>
                <a class="panda panda-cog"></a>
            </div>
        </div>
        <div class="tm-panel-header sh-products uk-form">
            {{ filter_form.exist.label }}: {{ filter_form.exist }}
            {{ filter_form.published.label }}: {{ filter_form.published }}
            <span>
                <label class="uk-margin-left">از قیمت (تومان)</label>
                {{ filter_form.min_price }} تا {{ filter_form.max_price }}
            </span>
            <span class="sh-search uk-search">{{ filter_form.search }}</span>
            <div class="uk-float-left">
                <label class="uk-margin-left">تعداد نمایش</label>
                {{ filter_form.product_per_page }}
            </div>
        </div>
        {{ filter_form.trash }}
        <table class="uk-table sh-all-product-table">
            <thead>
            <tr>
                <th>ردیف</th>
                <th>کد محصول</th>
                <th>نام محصول</th>
                <th>رسته و گروه</th>
                <th>قیمت</th>
                <th>تاریخ ثبت</th>
                <th>آخرین ویرایش</th>
                <th>وضعیت</th>
                <th>عملیات</th>
            </tr>
            </thead>
            <tbody id="products"></tbody>
        </table>
        <div class="tm-panel-footer-small uk-clearfix">
            <div class="uk-float-right" id="table-footer-info">
                <span class="product record">{{ count_products }}</span>
                محصول ثبت شده
                <span class="product publish">{{ count_products_published }}</span>
                منتشر شده
                <span class="product Unpublished">{{ count_products_no_published }}</span>
                منتشر نشده
            </div>
            <ul class="sh-pagination uk-pagination uk-float-left" id="paginator"></ul>
        </div>
    </div>
{% endblock content %}
{% block modal %}
{% endblock %}
{% block uikit_js %}
    <script src="{% static 'js/paginator.js' %}"></script>
    <script src="{% static 'js/products.js' %}"></script>
    <script src="{% static 'js/jquery.selectBox.js' %}"></script>
{% endblock %}
{% block js_code %}
    <script>
        csrf_token = '{{ csrf_token }}';
        perm = true;
        content_product = true;
        supply_unit_perm = true;

        $('#id_exist').selectBox({
            menuTransition: 'fade',
            topPositionCorrelation: '0',
            menuSpeed: 'fast'
        });
        $('#id_published').selectBox({
            menuTransition: 'fade',
            menuSpeed: 'fast'
        });
        $('#id_product_per_page').selectBox({
            menuTransition: 'fade',
            topPositionCorrelation: '0',
            menuSpeed: 'fast'
        });

        paginator(1);
        $(".selectBox-dropdown-menu").mCustomScrollbar({theme: "dark-thin"});
        aside_dynamic('manage_products', 'manage_products_all');
    </script>
{% endblock %}

templates/product/productstrash.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <h2>داشبورد</h2>
    <ul class="tm-breadcrumb uk-breadcrumb">
        <li><a href=""><i class="panda panda-home"></i></a></li>
        <li><span>پنل مدیریت</span></li>
        <li><span>محصولات</span></li>
        <li class="uk-active"><span>محصولات پاک شده</span></li>
        <li class="uk-float-left"><span id="tm-date-and-time"></span></li>
    </ul>
    <div class="uk-panel uk-panel-box uk-panel-box-primary">
        <div id="dash-sh-content">
            <h3 class="uk-panel-title"><i class="panda panda-folder-open"></i>محصولات پاک شده</h3>
            <div class="tm-panel-header sh-products uk-form">
                <!--
            <a href="{% url 'productList' %}">محصولات</a>
        -->
                <label class="uk-float-right uk-margin-left">مرتب سازی</label>
                {{ filter_form.exist }}
                {{ filter_form.published }}
            <span>
                <label class="uk-float-right uk-margin-left">از قیمت (تومان)</label>
                {{ filter_form.min_price }}
                تا
                {{ filter_form.max_price }}
            </span>
                <span class="sh-search uk-search">{{ filter_form.search }}</span>
                <div class="uk-float-left">
                    <label class="uk-float-right uk-margin-left">تعداد نمایش</label>
                    {{ filter_form.product_per_page }}
                </div>
            </div>
            {{ filter_form.trash }}
            <table class="uk-table uk-table-striped sh-trashed-table">
                <thead>
                <tr>
                    <th>ردیف</th>
                    <th>کد محصول</th>
                    <th>نام محصول</th>
                    <th>رسته و گروه</th>
                    <th>قیمت</th>
                    <th>تاریخ ثبت</th>
                    <th>آخرین تاریخ ویرایش</th>
                    <th>عملیات</th>
                </tr>
                </thead>
                <tbody id="products"></tbody>
            </table>
            <div class="tm-panel-footer-small uk-clearfix">
                <ul class="uk-pagination uk-float-left" id="paginator"></ul>
            </div>
        </div>
    </div>

{% endblock content %}
{% block uikit_js %}
    <script src="{% static 'js/paginator.js' %}"></script>
    <script src="{% static 'js/jquery.selectBox.js' %}"></script>
{% endblock %}
{% block js_code %}
    <script>
        aside_dynamic ('manage_products', 'manage_products_trashed');
        comboBox('#id_exist, #id_published, #id_product_per_page');
        comboBox('.combo-large', 'combo-large');
        $(".sbOptions").mCustomScrollbar({theme:"dark-thin"});
        csrf_token = '{{ csrf_token }}';
        paginator(1);
    </script>
{% endblock %}